spring.application.name=backend-consultas
spring.datasource.url=jdbc:h2:file:./data/consultas
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=kondrasz
spring.datasource.password=Impala@666
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

